# Generated by Django 5.2.5 on 2025-08-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_instagramstory_options_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedbacks'},
        ),
    ]
