# Generated by Django 5.2.5 on 2025-08-16 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_country_options_alter_customerfeedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('file', ' file'), ('music', 'music'), ('video', 'video')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic', 'heif', 'doc', 'pdf', 'mp3', 'mp4', 'flac'])]),
        ),
    ]
