# Generated by Django 5.2.5 on 2025-08-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_address_alter_user_phone_number_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='verificationotp',
            options={'verbose_name': 'Verification Otp', 'verbose_name_plural': 'Verification Otps'},
        ),
    ]
