# Generated by Django 5.2.5 on 2025-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verificationotp_is_confirmed_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationotp',
            name='type',
            field=models.CharField(choices=[('register', 'register'), ('password_reset', 'password')]),
        ),
    ]
