# Generated by Django 5.2.5 on 2025-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_verificationotp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationotp',
            name='type',
            field=models.CharField(choices=[('register', 'register'), ('reset-password', 'reset-password')]),
        ),
    ]
