# Generated by Django 5.2.5 on 2025-08-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0010_remove_product_image_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product'),
        ),
    ]
