# Generated by Django 5.2.5 on 2025-08-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_discount_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('payme', 'payme'), ('cash', 'cash'), ('click', 'click')], max_length=20, null=True),
        ),
    ]
