# Generated by Django 5.2.5 on 2025-08-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='products',
        ),
    ]
