# Generated by Django 5.2.5 on 2025-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytraffice',
            name='high',
            field=models.FloatField(help_text='In meters'),
        ),
        migrations.AlterField(
            model_name='deliverytraffice',
            name='weight',
            field=models.FloatField(help_text='In kilogram'),
        ),
        migrations.AlterField(
            model_name='deliverytraffice',
            name='width',
            field=models.FloatField(help_text='In meters'),
        ),
    ]
