# Generated by Django 5.2.5 on 2025-08-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_deliverytraffice_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytraffice',
            name='high',
        ),
        migrations.RemoveField(
            model_name='deliverytraffice',
            name='width',
        ),
    ]
