# Generated by Django 5.2.5 on 2025-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_deliverytraffice_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
