# Generated by Django 5.2.5 on 2025-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_branch_latitude_alter_branch_longtitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytraffice',
            name='delivery_time',
            field=models.DurationField(help_text='in hours'),
        ),
    ]
