# Generated by Django 5.2.5 on 2025-08-14 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_instagramstory_options_alter_media_options_and_more'),
        ('products', '0002_product_brand_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Brand Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media'),
        ),
    ]
