# Generated by Django 5.2.5 on 2025-08-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_parent',
        ),
    ]
