# Generated by Django 5.2.5 on 2025-08-18 09:47

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, help_text='discount in percentage', null=True, validators=[products.models.discount_validator]),
        ),
    ]
